apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  labels:
    app: todo-backend
data:
  DB_HOST: {{ .Values.backend.database.host | quote }}
  DB_PORT: {{ .Values.backend.database.port | quote }}
  DB_NAME: {{ .Values.backend.database.name | quote }}
