apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: todo-backend-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: todo-backend-db
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: todo-staging-db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: todo-staging-db
        property: password
