apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-canary
  labels:
    app: todo-frontend
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: ClusterIP
