frontend:
  replicaCount: 1

  image:
    repository: todo-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 80

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

backend:
  replicaCount: 1

  image:
    repository: todo-backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8000

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  database:
    host: ""
    port: 3306
    name: todo_db

ingress:
  enabled: false
  className: alb
  scheme: internet-facing
  targetType: ip
  host: ""
  healthcheckPath: /
