frontend:
  replicaCount: 1

  image:
    repository: 275839157288.dkr.ecr.ap-south-1.amazonaws.com/todo-frontend
    tag: 8753de0f41161e6a29e0912690fdf6c767e1a760

backend:
  replicaCount: 1

  image:
    repository: 275839157288.dkr.ecr.ap-south-1.amazonaws.com/todo-backend
    tag: 8753de0f41161e6a29e0912690fdf6c767e1a760

  database:
    host: todo-staging-mysql.cvm42esgu4mv.ap-south-1.rds.amazonaws.com
    port: 3306
    name: todo

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  host: "www.devopslok.in"
  certificateArn: "arn:aws:acm:ap-south-1:275839157288:certificate/0def636e-7d0e-4ad4-a622-9f1f4d5dd725"
  healthcheckPath: /
