frontend:
  replicaCount: 1

  image:
    repository: todo-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 80

backend:
  replicaCount: 1

  image:
    repository: todo-backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 8000

  database:
    host: ""
    port: 3306
    name: todo_db

ingress:
  enabled: false
  className: alb
  scheme: internet-facing
  targetType: ip
  host: ""
  healthcheckPath: /
