frontend:
  replicaCount: 1

  image:
    repository: 275839157288.dkr.ecr.ap-south-1.amazonaws.com/todo-frontend
    tag: f515c51c5168367275df7750ec635f8156ccb435

backend:
  replicaCount: 1

  image:
    repository: 275839157288.dkr.ecr.ap-south-1.amazonaws.com/todo-backend
    tag: f515c51c5168367275df7750ec635f8156ccb435

  database:
    host: todo-staging-mysql.cvm42esgu4mv.ap-south-1.rds.amazonaws.com
    port: 3306
    name: todo

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  host: ""
  healthcheckPath: /
